Fix static analyzer warnings.
readdle/PLzmaSDK pull request #2
Opened 2022-09-29 15:54 UTC by apodrugin

2022-10-04 19:31 UTC, pastey requested changes
Два предложения

2022-10-04 19:31 UTC, pastey commented on src/CPP/7zip/Compress/Bcj2Coder.cpp
> -    outSizeProcessed += curSize;
Может тут тоже применить схему с ифдеф? Очково что появятся потом кода

```
  // Added the 'ifndef' below to suppress clang analyzer 'Value stored to 'cur' is never read' warning.
  // Actually we can remove 'cur += 8' below, but if some code will be added in future, then we will
  // be in truble.
```

2022-10-05 08:02 UTC, apodrugin commented on src/C/Lzma2Enc.c
> +  {
Улучшу

2022-10-05 09:03 UTC, apodrugin commented
Внес правки, прошу смотреть.

2022-10-05 14:59 UTC, merged